locals {
    harness_connectors = {
        github = {
            crizstian = {
                enable             = true
                description        = "Connector generated by terraform harness provider"
			    connection_type    = "Account"
                url                = "https://github.com/Crizstian"
                delegate_selectors = ["local-environment"]
                validation_repo    = "harness-as-code"
                account_level      = false
                org_level          = false
                proj_level         = false
                credentials = {
                    http = {
                        username  = "crizstian"
                        token_ref = var.harness_connectors_crizstian_github_token
                    }
                }
            }
        }
        docker = {
            crizstian = {
                enable             = true
                description        = "Connector generated by terraform harness provider" 
                tags               = ["local:environment"]
                delegate_selectors = ["local-environment"]
                org_id             = ""
			    type               = "DockerHub"
			    url                = "https://registry.hub.docker.com/v1/"
                credentials        = {
                    username     = "crizstian"
				    password_ref = var.harness_connectors_crizstian_docker_token
                }
            }
        }
        k8s = {
            docker-desktop = {
                enable             = false
                description        = "Connector generated by terraform harness provider" 
                tags               = ["local:environment"]
                delegate_selectors = ["local-environment"]
                org_id             = ""
            }
        }
    }
}