locals {
    harness_pipelines = {
        feature-flags-app = {
            org_id      = var.harness_platform_project.organization_id
            project_id  = var.harness_platform_project.id
            yaml        = "pipeline.yml"
            description = "Pipeline generated by terraform harness provider"
        }
    }
}