variable "aws_anka_enabled" {
    default = false
}
variable "macos_ip_address" {
    default = ""
}
variable "harness_platform_api_key" {
    sensitive = true
}
variable "harness_platform_account_id" {
    sensitive = true
}
variable "harness_platform_organization" {
    default = {
        name        = "Cristian-Lab-Org"
        description = "Organization generated by terraform harness provider"
    }
}
variable "harness_platform_project" {
    default = {
        name        = "iOS-FaceApp"
        description = "Project generated by terraform harness provider"
    }
}

locals {
    harness_delegate = {
        docker = {
            osx-docker-desktop = {
                enable                 = true
                description            = "Delegate deployed and generated by terraform harness provider"
                size                   = "LAPTOP"
                tags                   = ["local-environment"]
                clusterPermissionType  = "CLUSTER_ADMIN"
                customClusterNamespace = "harness-delegate-ng"
            }
            osx-docker-remote = {
                enable                 = true
                description            = "Delegate deployed and generated by terraform harness provider"
                size                   = "LAPTOP"
                tags                   = ["local-environment"]
                clusterPermissionType  = "CLUSTER_ADMIN"
                customClusterNamespace = "harness-delegate-ng"
                remote                 = {
                    user        = "ec2-user"
                    host        = var.aws_anka_enabled ? data.terraform_remote_state.harness_anka.0.outputs.anka-vm.ip_address : var.macos_ip_address
                    private_key = "anka"
                    type        = "anka"
                }
            }
        }
        k8s = {
            k8s-docker-desktop = {
                enable                 = false
                description            = "Delegate deployed and generated by terraform harness provider"
                size                   = "LAPTOP"
                tags                   = ["local-environment"]
                clusterPermissionType  = "CLUSTER_ADMIN"
                customClusterNamespace = "harness-delegate-ng"
            }
        }
    }  
}