variable "harness_platform_api_key" {
    sensitive = true
}
variable "harness_platform_account_id" {
    sensitive = true
}
variable "harness_platform_organization" {
    default = {
        name        = "Cristian-Lab-Org"
        description = "Organization generated by terraform harness provider"
    }
}
variable "harness_platform_project" {
    default = {
        name        = "iOS-FaceApp"
        description = "Project generated by terraform harness provider"
    }
}

variable "harness_delegate" {
    default = {
        docker = {
            osx-docker-desktop = {
                enable                 = true
                description            = "Delegate deployed and generated by terraform harness provider"
                size                   = "LAPTOP"
                tags                   = ["local-environment"]
                clusterPermissionType  = "CLUSTER_ADMIN"
                customClusterNamespace = "harness-delegate-ng"
            }
        }
        k8s = {
            k8s-docker-desktop = {
                enable                 = true
                description            = "Delegate deployed and generated by terraform harness provider"
                size                   = "LAPTOP"
                tags                   = ["local-environment"]
                clusterPermissionType  = "CLUSTER_ADMIN"
                customClusterNamespace = "harness-delegate-ng"
            }
        }
    }
}